apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "helm-ui.labels" . | nindent 4 }}
  namespace: ms
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-ui.selectorLabels" . | nindent 8 }}
    spec:
       containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}
          ports:
          - containerPort: {{ .Values.service.port }}