apiVersion: apps/v1
kind: Deployment
metadata:
  name:  zuul-api
  namespace: ms
  labels:
    app:  zuul-api
spec:
  selector:
    matchLabels:
      app: zuul-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  zuul-api
    spec:
      containers:
      - name:  zuul-api
        image:  dharma006/zull:apigateway
        ports:
        - containerPort:  9999
          name:  zuul-api
      affinity:
        podAffinity: 
         requiredDuringSchedulingIgnoredDuringExecution: 
         - labelSelector:
             matchExpressions:
             - key: app 
               operator: In 
               values:
               - react-ui
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-service
  namespace: ms
spec:
  selector:
    app: zuul-service
  type: NodePort
  ports:
  - name: zuul-service
    protocol: TCP
    port: 9999
    targetPort: 9999 
    nodePort: 32470