replicaCount: 1

image:
  repository: dharma006/zull:ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  name: react-ui

containers:
  name:  react-ui
  