apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
     {{- include "shoecharts.labels" . |
     nindent 4}}
  namespace: ms
spec:
  selector:
    {{- include "shoecharts.selectorLabels" . |
    nindent 6 }}
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.name }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}